Removed a if statement from CollectCargo and DiscardCargo
FRCTeam3255/Robot2022-V pull request #120
Opened 2022-10-29 18:21 UTC by Adam-Walls077

closes #24

2022-10-29 21:49 UTC, ACat701 requested changes
Both commands still need to retract the intake. The issue is that the if statement is redundant, because if its already retracted, retracting it again won't do anything

2022-10-29 22:51 UTC, TaylerUva requested changes
To specify we need the internals of the if statement just not the it itself

2022-10-30 00:47 UTC, TaylerUva requested changes
Remove the unused boolean calls

2022-10-30 00:47 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Cargo/CollectCargo.java
> +        subIntake.isDeployed();
This is a boolean so it doesn't do anything on its own

2022-10-30 00:47 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Cargo/DiscardCargo.java
> +      subIntake.isDeployed();
This is a boolean so it doesn't do anything on its own

2023-08-06 18:15 UTC, closed without merging