New autos
FRCTeam3255/Robot2022-V pull request #130
Opened 2022-11-02 20:22 UTC by IanSzalai

2022-11-07 21:15 UTC, IanSzalai commented
this is the final code that ran at Beach Blitz

2022-11-27 18:41 UTC, TaylerUva requested changes

2022-11-27 18:41 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Cargo/ShootCargo.java
> +    isShooterReady = subShooter.isMotorAtSpeed() && buffer > 15;
This should be a robot preference

2022-11-27 18:42 UTC, TaylerUva approved these changes

2022-11-27 18:42 UTC, merged

2022-11-27 18:43 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Cargo/ShootCargo.java
> +    isShooterReady = subShooter.isMotorAtSpeed() && buffer > 15;
Created issue for this #131