Added Magic Climb
FRCTeam3255/Robot2022-V pull request #29
Opened 2022-10-22 20:44 UTC by ACat701

Closes #26

2022-10-23 04:24 UTC, IanSzalai commented
i have no idea how you messed up the formatting that badly. it's fixed now, but that was horrible

2022-10-23 04:41 UTC, IanSzalai requested changes
I don't think that you can use instant commands in a sequential command group like this. the way a sequential command group works, it will do one command, then when that command is complete, it will move on to the next command. instant commands by nature instantly complete, so there is never any time for the climber to actually get to a position.

what i think you can do is instead of using instant commands, use `RunCommand()`, then decorate it at the end with `.until()`. eg:

```java
new RunCommand(
    () -> subClimber.setClimberPosition(
        prefClimber.climberPerpendicularMinPos))
            .until(() -> subClimber.getMinSwitch())
```

`RunCommand()` will run continuously and never end on its own. `.until()` will interrupt the command when that condition is true. one difficulty with this method may be getting a good condition to determine when the climber is in the right position. I would probably want to add a method in the climber subsystem for that.


Here's a different solution: time about how long it takes from the climber to get from the bottom to the top. let this time be T. 

```java
new InstantCommand(
     () -> subClimber.setClimberPosition(
        prefClimber.climberPerpendicularMinPos)),

new WaitCommand(T)
```

`WaitCommand(T)` literally just does nothing for T seconds. This would just set the position, then wait. I do like this solution because there should be some delay between the robot's actions, and instead of bothering to implement the delay on its own it could just be a basic part of the command. The downside is that this implementation does not have the same potential for high level tuning, but I doubt that that will come up this year.

2022-10-23 05:21 UTC, IanSzalai commented on src/main/java/frc/robot/RobotContainer.java
> +    conDriver.btn_Start.whenPressed(comMagicClimb);
this should be a `.whileHeld()` so if something goes wrong the driver can very easily and quickly stop it

2022-10-25 03:01 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Climber.java
> +  // I don't want another disgard moment
bruh

2022-10-25 03:03 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Climber.java
> +    }
you can just `return getClimberEncoderCounts() > prefClimber.climberOptimalAnglingPosition.getValue();` without the if statement

2022-10-25 03:03 UTC, IanSzalai commented on src/main/java/frc/robot/subsystems/Climber.java
> +  public boolean canAngle() {
this could be named more verbosely, something that references 'optimal angling position' could work well I think

2022-10-26 02:46 UTC, ACat701 commented
This works on the robot, but the command will restart if the button is still held once it ends; will come up with a solution later

2022-10-26 04:23 UTC, IanSzalai commented
Potential solution: press btn to start command, press button to end command (if necessary)
* Pros:
  * quick and easy to implement
  * defined behavior
* Cons:
  * Slightly worse safety, since it's not a deadman switch

really since this command isn't going from rung to rung it's not a big deal if the safety isn't all there. plus with the upcoming upgrades to the climber it may become consistent enough where the estop button is safety enough

possible implementation:
```java
conDriver.btn_Start
    .whenPressed(comMagicClimb)
    .cancelWhenPressed(comMagicClimb);
```
i think this won't just start then immediately end the command, but we'd need to test it

2022-10-29 01:03 UTC, ACat701 commented
.toggleWhenPressed();

2023-08-06 18:15 UTC, closed without merging